replicaCount: 1

image:
  repository: node-app
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 3000

env:
  MONGO_URI: "mongodb://mongodb:27017/taskManagerDB"
  REDIS_URL: "redis://redis:6379"
  RABBITMQ_URL: "amqp://rabbitmq"
